language: python
python:
- '3.6'
services: postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=2.1.3 DB=postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database Tdd;' -U postgres
  - psql -c "CREATE USER rajatkhemka WITH PASSWORD 'admin123'" -U postgres

script: python manage.py test
