language: python
python:
- '3.6'
services: postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=1.11.3 DB=postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE xiaole;" -U postgres
  - psql -c "CREATE USER xiaole WITH CREATEUSER PASSWORD 'Besthuaihua@22';" -U postgres
script:
  # python manage.py migrate
  # python manage.py test lists/
  # python manage.py test functional_tests/
  - coverage run manage.py test lists/
  - coverage run manage.py test functional_tests/
after_success:
  coveralls
