language: python
python:
- '3.6'
services: postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - BUILD_ON_TRAVIS=true
addons:
  firefox: "54.0.1"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
#- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
#- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin/
#- export CHROME_BIN=chromium-browser
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE Tdd;" -U postgres
  - psql -c "CREATE USER rajatkhemka WITH CREATEUSER PASSWORD '';" -U postgres
script:
  - python manage.py test lists/ --keepdb
  - python manage.py test functional_tests/ --keepdb
