language: python

python:
- 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

env:
  global:
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=1.11.3 DB=postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt

script: python manage.py test
