language: python

python:
- 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
services: postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database Tdd;' -U postgres
script: python manage.py test
