# Generated by Django 2.1.3 on 2018-11-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20181127_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(blank=True,on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
